var sbc = new StoryboardController(new Listener());
sbc.addEvent("A");
sbc.addEvent("B");
sbc.addActor("Cube","abcd",{tx:0, ty:0, tz:0, rx:0, ry:0,rz:0,sx:1,sy:1,sz:1});
sbc.addActor("Sphere","efgh",{tx:0, ty:0, tz:0, rx:0, ry:0,rz:0,sx:1,sy:1,sz:1});
sbc.startAddSegment(1,3);
sbc.setActorForNewSegment(1);
sbc.setDescriptionForNewSegment("1-A");
sbc.setDurationForNewSegment(4);
sbc.addSegment();
sbc.startAddSegment(3,4);
sbc.setActorForNewSegment(2);
sbc.setDescriptionForNewSegment("A-B");
sbc.setDurationForNewSegment(3);
sbc.addSegment();
sbc.startAddSegment(1,4);
sbc.setActorForNewSegment(1);
sbc.setDescriptionForNewSegment("1-B");
sbc.setDurationForNewSegment(5);
sbc.addSegment();
sbc.startAddSegment(4,2);
sbc.setActorForNewSegment(2);
sbc.setDescriptionForNewSegment("B-2");
sbc.setDurationForNewSegment(2);
sbc.addSegment();
sbc.processStoryboard();
